def mainMenu():
    print("********************************************************")
    print("1. Create a new account")
    print("2. Login")
    print("3. Quit")
    print("********************************************************")
    return input("Please Choose a number: ")

def manageAccountMenu():
    print("********************************************************")
    print("1. Edit my details")
    print("2. Add a friend")
    print("3. View all my friends")
    print("4. View all my messages")
    print("5. Message a friend")
    print("6. Block a user")
    print("7. View blocked users")
    print("8. Remove a friend")
    print("9. <- Go back ")
    print("********************************************************")
    return input("Please Choose a number: ")
